### ISSUE TITLE
登录时候提示token不对

### ISSUE THREAD

**Issue by ccsds** [wechaty/java-wechaty-getting-started#27]
我将项目拉到了eclipse里，将以puppet_padplus_开头的token填入了DingDongBot类中运行后提示
`17:13:47.123 [main]INFO  io.github.wechaty.user.manager.PuppetManager-[23]  - PuppetManager resolveInstance({"name":"Wechaty","puppet":"io.github.wechaty.grpc.GrpcPuppet","puppetOptions":{"token":"puppet_padplus_c7ace10a40b891cd","name":"DEFAULT"}})
17:13:47.292 [main]INFO  org.reflections.Reflections-[229]  - Reflections took 156 ms to scan 5 urls, producing 159 keys and 1536 values 
17:13:49.760 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[154]  - cannot get ip by token, check token
`

**Comment by zeal607** [comment]
> 我将项目拉到了eclipse里，将以puppet_padplus_开头的token填入了DingDongBot类中运行后提示 `17:13:47.123 [main]INFO io.github.wechaty.user.manager.PuppetManager-[23] - PuppetManager resolveInstance({"name":"Wechaty","puppet":"io.github.wechaty.grpc.GrpcPuppet","puppetOptions":{"token":"puppet_padplus_c7ace10a40b891cd","name":"DEFAULT"}}) 17:13:47.292 [main]INFO org.reflections.Reflections-[229] - Reflections took 156 ms to scan 5 urls, producing 159 keys and 1536 values 17:13:49.760 [main]ERROR io.github.wechaty.grpc.GrpcPuppet-[154] - cannot get ip by token, check token `

找到解决办法了吗
