### ISSUE TITLE
 如何获取自己token呢？环境变量配置是知道的。

### ISSUE THREAD

**Issue by panda-bear** [wechaty/java-wechaty-getting-started#37]
设置token 是这个export WECHATY_PUPPET_SERVICE_TOKEN=your_token_at_here，没毛病。tonken没设置对，导致如下：
<img width="770" alt="image" src="https://user-images.githubusercontent.com/31984233/180655698-3d3caa86-43de-4439-9434-fee94485d54e.png">

**Comment by panda-bear** [comment]
token是不是需要花钱购买？？？ 入口在哪？

**Comment by ilh-github** [comment]
> 

同问

**Comment by panda-bear** [comment]
原生基于web协议的wecharty，是不需要token；目前腾讯官方大部分都禁掉网页版微信了。
所以目前都是puppet方式模拟客户端操作微信，自然就诞生了提供商，各自的实现及对应云服务puppet service. 需要去购买的，官网里能找到地址好几个。

**Comment by ilh-github** [comment]
原生的现在基于UOS有可以只用了，代码能适配下吗？

**Comment by Xlong99** [comment]
老哥可以发一个购买地址吗
