### ISSUE TITLE
THE semver for Java Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/java-wechaty-getting-started#8]
Currently, our Wechaty project is using the semver, start from version 0.0.1.

The latest wechaty on npm is v0.39

So I'd like to suggest that our Java Wechaty follow the same versioning style, and start from version 0.1.0

Also, npm and pip all have a dev version so that we can publish a version for the beta users, and at the same time, the release user will not see the beta version.

To archive that, npm has the `@next` version instead of the `latest`, and the pip has a `-dev` for PRE-RELEASE.

It would be great if our Java Wechaty can use the same method to differentiate those two published versions, if the maven system has the same pattern for the publishing.

**Comment by diaozxin007** [comment]
mvn has snapshot version.

**Comment by huan** [comment]
That's great!

Then we can follow the same semver versioning rule and the publish patterns from the Wechaty Org for our Java Wechaty:

1. odd minor version number will be CI/CD to `snapshot` for beta users.
1. even minor version number will be CI/CD to the production.
